# Generated by Django 5.1.1 on 2024-12-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], default='dog and cat', max_length=100),
            preserve_default=False,
        ),
    ]
