# Generated by Django 5.1.1 on 2024-12-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='animal',
        ),
    ]
